// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4EGpuOqepECYD-JPULyOcBOCE5bHxLs',
    appId: '1:271306758952:web:666054d91c05a8a616ce1d',
    messagingSenderId: '271306758952',
    projectId: 'lost-project-8b4f4',
    authDomain: 'lost-project-8b4f4.firebaseapp.com',
    storageBucket: 'lost-project-8b4f4.appspot.com',
    measurementId: 'G-G82V48SVNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxrDmnHSPniGs2QUtmii04gJQ4ikroAzA',
    appId: '1:271306758952:android:279eb215bb94217d16ce1d',
    messagingSenderId: '271306758952',
    projectId: 'lost-project-8b4f4',
    storageBucket: 'lost-project-8b4f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLJmThczFGgfPAkK4pE2_ADHDV1mbIfM',
    appId: '1:271306758952:ios:b9b8c7078468494116ce1d',
    messagingSenderId: '271306758952',
    projectId: 'lost-project-8b4f4',
    storageBucket: 'lost-project-8b4f4.appspot.com',
    iosBundleId: 'com.example.lostProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLJmThczFGgfPAkK4pE2_ADHDV1mbIfM',
    appId: '1:271306758952:ios:b9b8c7078468494116ce1d',
    messagingSenderId: '271306758952',
    projectId: 'lost-project-8b4f4',
    storageBucket: 'lost-project-8b4f4.appspot.com',
    iosBundleId: 'com.example.lostProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4EGpuOqepECYD-JPULyOcBOCE5bHxLs',
    appId: '1:271306758952:web:5f78c4ebf9a2a97816ce1d',
    messagingSenderId: '271306758952',
    projectId: 'lost-project-8b4f4',
    authDomain: 'lost-project-8b4f4.firebaseapp.com',
    storageBucket: 'lost-project-8b4f4.appspot.com',
    measurementId: 'G-KXQZSPNG1C',
  );
}
